name: DevSecOps Pipeline
on:
  push:
    branches: [ main ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.0

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@v0

    - name: Install Grype
      uses: anchore/scan-action/download-grype@v3

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: SAST
      run: make sast

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
        chmod +x /usr/local/bin/gitleaks
    
    - name: Secrets Scan
      run: bash scripts/secrets.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    
    - name: Upload Secrets Report
      uses: actions/upload-artifact@v4
      with:
        name: secrets-report
        path: reports/secrets-report.json
      if: always()

    - name: Dependency Scan
      run: make sca
      continue-on-error: true

    - name: Build Image
      run: make build
      continue-on-error: true

    - name: Container Scan
      run: make image-scan
      continue-on-error: true

    - name: Generate SBOM
      run: make sbom
      continue-on-error: true

    - name: Sign Image
      run: make sign
      continue-on-error: true

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/